[IA]
IMAGE_SIZE = [256,256]
SAVED_N_BEST = 2

[IA.Model]
PATH_CSV = "./datas/tela_botanica_export.csv"
DATAS_PATH = './datas/tela_botanica_images_min'
PATH_RESIZED_SAVE = './datas/save_resized.npy'
MODEL_NAME_H5 = "model.h5"
MODEL_NAME= "model"

[WEB]
PORT = 8088
DEBUG = true