version: "3.3"
services:

  web:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    entrypoint: python3 main.py
    ports:
      - "8088:8088"
    networks:
      - backend
    volumes:
      - .:/var/Jardins-Angevins
    depends_on:
      - database
    environment:
      - CQLENG_ALLOW_SCHEMA_MANAGEMENT=1


  database:
    image: "cassandra:4.1"
    networks:
      - backend


networks:
  backend:

volumes:
  v: